# This is a basic workflow to help you get started with Actions

name: CITestAction

# Controls when the action will run. 
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: "YYYYMMDDhhmmss"
          utcOffset: "+08:00"
      - name: sed test
        run: |
          sed -i -e 's/"version": "(.*)?"/"version": "$1-beta${{ steps.current-time.outputs.formattedTime }}",/g' package.json
      - name: cat
        run: cat package.json
